# Generated by Django 3.2.13 on 2022-05-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeuser',
            old_name='name',
            new_name='users_name',
        ),
    ]
