# Generated by Django 3.2.13 on 2022-05-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220519_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='recipeuser',
            name='user_permissions',
        ),
    ]
